/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import * as THREE from "three";
import { animate, useMotionValue } from "framer-motion";
import {motion} from "framer-motion-3d"
import { useFrame } from "@react-three/fiber";
export function Finalscene(props) {
  const {section} = props
  const { nodes, materials } = useGLTF("models/screening.glb");
  const texture = useTexture("./finalBake.jpg");
  const videoTexture = useVideoTexture("videos/coding.mp4")
  texture.flipY = false
  texture.encoding = THREE.sRGBEncoding
  const textureMaterial = new THREE.MeshStandardMaterial({
    map:texture,
    transparent:true,
    opacity:1
  });


  const textureOpacity = useMotionValue(0);

  useEffect(()=>{
    animate(textureOpacity, section === 0 ? 1 : 0,{
      duration:0.8,
    });
  },[section])

  useFrame(()=>{
    textureMaterial.opacity = textureOpacity.get();
  })

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
      <mesh
          name="screen"
          castShadow
          receiveShadow
          geometry={nodes.screen.geometry}
          position={[-0.29, 0.928, -1.624]}
        >
          <meshBasicMaterial map={videoTexture} toneMapped={false} />
        </mesh>
        <motion.mesh
          name="Carpet"
          castShadow
          receiveShadow scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
          geometry={nodes.Carpet.geometry}
          material={textureMaterial}
          position={[-0.062, 0.018, 1.006]}
        ></motion.mesh>
        <motion.group
          name="POT__0"
          position={[1.46, 0.105, -1.479]}
          scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Potmesh"
            castShadow
            receiveShadow
            geometry={nodes.Potmesh.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Potmesh_1"
            castShadow
            receiveShadow
            geometry={nodes.Potmesh_1.geometry}
            material={textureMaterial}
          />
        </motion.group>
        <motion.group
          name="JoystickMesh"
          scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
          position={[-1.059, 0.973, -1.25]}
          rotation={[-3.137, 0.364, 0.04]}
        >
          <mesh
            name="Joystickeshes"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_1"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_2"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_3"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_4"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_4.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_5"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_5.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_6"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_6.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_7"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_7.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_8"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_8.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_9"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_9.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_10"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_10.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Joystickeshes_11"
            castShadow
            receiveShadow
            geometry={nodes.Joystickeshes_11.geometry}
            material={textureMaterial}
          />
        </motion.group>
        <motion.mesh
          name="Monitor"
          scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
          castShadow
          receiveShadow
          geometry={nodes.Monitor.geometry}
          material={textureMaterial}
          position={[-0.29, 0.928, -1.624]}
        ></motion.mesh>
        <mesh
          name="table"
          castShadow
          receiveShadow
          geometry={nodes.table.geometry}
          material={textureMaterial}
          position={[-0.29, -0.002, -1.356]}
        />
        <mesh
          name="keyboard"
          castShadow
          receiveShadow
          geometry={nodes.keyboard.geometry}
          material={textureMaterial}
          position={[-0.332, 0.954, -1.278]}
          scale={0.728}
        />
        <mesh
          name="Mousegroup"
          castShadow
          receiveShadow
          geometry={nodes.Mousegroup.geometry}
          material={textureMaterial}
          position={[0.047, 0.928, -1.246]}
          scale={0.803}
        />
        <motion.group name="Chair" position={[-0.226, 0.478, -0.742]}>
          <mesh
            name="ChairMesh"
            castShadow
            scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
            receiveShadow
            geometry={nodes.ChairMesh.geometry}
            material={textureMaterial}
          />
          <mesh
            name="ChairMesh_1"
            castShadow
            receiveShadow
            geometry={nodes.ChairMesh_1.geometry}
            material={textureMaterial}
          />
        </motion.group>
        <mesh
          name="Desktop"
          castShadow
          receiveShadow
          geometry={nodes.Desktop.geometry}
          material={textureMaterial}
          position={[0.471, 1.239, -1.438]}
        />
        <group name="Plane">
          <mesh
            name="Plane_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane_2.geometry}
            material={textureMaterial}
          />
        </group>
       
      </group>
    </group>
  );
}

useGLTF.preload("models/screening.glb");
useTexture.preload("./finalBake.jpg");
